// Auto-generated daily by GitHub Actions + Gemini. Do not edit manually.
// Last update: 2026-10-06 14:12 UTC
window.CENews = [
  {
    "id": "the-next-web-48e8e8a09a",
    "source": "The Next Web",
    "category": "Artificial Intelligence",
    "date": "2026-10-06T13:00:45+00:00",
    "title": "Europe’s Mistral launches Large 4 to challenge China’s lead in open AI models",
    "summary": "Mistral has released a preview of its massive trillion-parameter model, Mistral Large 4, positioning it as a leading open-weight system built outside China. Developers can already access the system via API ahead of the full model weight release.",
    "url": "https://thenextweb.com/news/mistral-releases-large-4-a-1-trillion-parameter-open-weight-ai-model",
    "image": "https://media.thenextweb.com/2026/05/Mistral-AI.avif"
  },
  {
    "id": "techcrunch-549ccc4aee",
    "source": "TechCrunch",
    "category": "Artificial Intelligence",
    "date": "2026-10-05T20:36:48+00:00",
    "title": "OpenAI will start watermarking ChatGPT’s text in the EU",
    "summary": "OpenAI is implementing digital watermarking for text and code generated by ChatGPT and Codex within the European Union to comply with strict regional AI transparency legislation.",
    "url": "https://techcrunch.com/2026/10/05/openai-will-start-watermarking-chatgpts-text-in-the-eu/",
    "image": "https://techcrunch.com/wp-content/uploads/2026/09/openai-getty.jpg?resize=1200,800"
  },
  {
    "id": "the-verge-c481fc93e0",
    "source": "The Verge",
    "category": "Artificial Intelligence",
    "date": "2026-10-06T14:12:04.204325+00:00",
    "title": "Google is about to remove free access to Gemini Flash and Pro",
    "summary": "Google is restricting free Gemini tier users exclusively to the Flash Lite model, requiring a paid subscription to access the standard Flash and Pro options.",
    "url": "https://www.theverge.com/ai-artificial-intelligence/1005451/google-gemini-free-flash-lite-only",
    "image": "https://platform.theverge.com/wp-content/uploads/sites/2/chorus/uploads/chorus_asset/file/25290329/STK255_Google_Gemini_A.jpg?quality=90&#038;strip=all&#038;crop=0,0,100,100"
  },
  {
    "id": "the-next-web-e0ad0d5e7b",
    "source": "The Next Web",
    "category": "Robotics",
    "date": "2026-10-06T14:05:41+00:00",
    "title": "Minerva Humanoids raises $10M for robots that do bomb disposal and rig work",
    "summary": "Robotics startup Minerva Humanoids has secured $10 million in pre-seed funding led by General Catalyst to develop advanced humanoid robots tailored for high-risk industrial and public safety jobs.",
    "url": "https://thenextweb.com/news/minerva-humanoids-10m-pre-seed-general-catalyst",
    "image": "https://media.thenextweb.com/2026/10/minerva-humanoids-roger-humanoid-robot-walking-dark-background.avif"
  },
  {
    "id": "techcrunch-9945cb5716",
    "source": "TechCrunch",
    "category": "Chips",
    "date": "2026-10-05T20:24:09+00:00",
    "title": "Etched fields funding offers at $40B+ valuation, sources say",
    "summary": "AI chip startup Etched is reportedly seeing massive investor interest with funding offers that could value the company at over $40 billion shortly after its previous raise.",
    "url": "https://techcrunch.com/2026/10/05/etched-fields-funding-offers-at-40b-valuation-sources-say/",
    "image": "https://techcrunch.com/wp-content/uploads/2026/07/Sequoia_Etched-Abhishek-Malani-Robert-Wachen-Sonya-Huang-Gavin-Uberti-copy.jpeg?resize=1200,846"
  },
  {
    "id": "techradar-bc753776ae",
    "source": "TechRadar",
    "category": "Cybersecurity",
    "date": "2026-10-06T12:15:53+00:00",
    "title": "ASOS 'hacked' live —all the latest as customers receive threatening alert",
    "summary": "Online retail giant ASOS faced an apparent security breach after mobile app users received unexpected and threatening push notifications titled 'ASOS Hacked'.",
    "url": "https://www.techradar.com/news/live/asos-apparent-hack-october-6",
    "image": "https://cdn.mos.cms.futurecdn.net/3YvbjphPM2sggk5cnCH5tK-1920-80.jpg"
  },
  {
    "id": "the-next-web-78c4d26a93",
    "source": "The Next Web",
    "category": "Developer Technology",
    "date": "2026-10-06T13:23:43+00:00",
    "title": "Zapata Quantum joins IBM Quantum Network to build quantum applications",
    "summary": "Quantum software firm Zapata Quantum has joined the IBM Quantum Network to leverage IBM's hardware infrastructure for enterprise client solutions.",
    "url": "https://thenextweb.com/news/zapata-quantum-ibm-quantum-network",
    "image": "https://media.thenextweb.com/2026/04/Zapata-Quantum.avif"
  },
  {
    "id": "techcrunch-a0e8c928a8",
    "source": "TechCrunch",
    "category": "Product Launches",
    "date": "2026-10-05T18:07:07+00:00",
    "title": "At 19, founder raises $11M for Ghost, maker of a $3,499 computer for personal AI",
    "summary": "A 19-year-old founder has raised $11 million to build Core, a specialized $3,499 personal computer designed specifically to host autonomous AI agents.",
    "url": "https://techcrunch.com/2026/10/05/at-19-ghost-founder-raises-11-million-to-build-a-3499-computer-for-your-personal-ai/",
    "image": "https://techcrunch.com/wp-content/uploads/2026/10/Ghost-team.png?resize=1200,803"
  },
  {
    "id": "techcrunch-82cd9e3ab1",
    "source": "TechCrunch",
    "category": "Artificial Intelligence",
    "date": "2026-10-05T19:33:53+00:00",
    "title": "Reflection debuts Beam, an open-weight AI model to rival Chinese models at lower compute cost",
    "summary": "Reflection has launched Beam, an open-weight model engineered to compete with foreign alternatives while enabling enterprises to build local AI factories using proprietary data.",
    "url": "https://techcrunch.com/2026/10/05/reflection-debuts-beam-a-open-weight-ai-model-to-rival-chinese-models-at-lower-compute-cost/",
    "image": "https://techcrunch.com/wp-content/uploads/2026/10/Reflection-AI-Beam.png?resize=1200,669"
  },
  {
    "id": "the-next-web-ffaab5a503",
    "source": "The Next Web",
    "category": "Software",
    "date": "2026-10-06T12:52:53+00:00",
    "title": "SAP agrees to acquire Belgian AI workforce startup TechWolf",
    "summary": "Enterprise software leader SAP has agreed to purchase TechWolf, integrating the Belgian startup's workforce skills-mapping AI platform into its ecosystem.",
    "url": "https://thenextweb.com/news/sap-acquires-techwolf-ai-workforce",
    "image": "https://media.thenextweb.com/2026/07/SAP-Locations-Walldorf-1.avif"
  }
];
