-- CryptoEngineer: Auth + Project submissions + Hire requests
-- Run this once in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.project_submissions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  category text not null,
  description text not null,
  project_url text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now()
);

create table if not exists public.project_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  company text,
  email text not null,
  budget text,
  timeline text,
  message text not null,
  status text not null default 'new' check (status in ('new','reviewing','closed')),
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

alter table public.profiles enable row level security;
alter table public.project_submissions enable row level security;
alter table public.project_requests enable row level security;

drop policy if exists "profiles own read" on public.profiles;
create policy "profiles own read" on public.profiles
for select to authenticated using (id = auth.uid() or public.is_admin());

drop policy if exists "submissions public approved read" on public.project_submissions;
create policy "submissions public approved read" on public.project_submissions
for select to anon, authenticated using (status = 'approved' or user_id = auth.uid() or public.is_admin());

drop policy if exists "submissions own insert" on public.project_submissions;
create policy "submissions own insert" on public.project_submissions
for insert to authenticated with check (user_id = auth.uid());

drop policy if exists "submissions own update" on public.project_submissions;
create policy "submissions own update" on public.project_submissions
for update to authenticated using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());

drop policy if exists "submissions admin delete" on public.project_submissions;
create policy "submissions admin delete" on public.project_submissions
for delete to authenticated using (public.is_admin());

drop policy if exists "requests own insert" on public.project_requests;
create policy "requests own insert" on public.project_requests
for insert to authenticated with check (user_id = auth.uid());

drop policy if exists "requests admin read" on public.project_requests;
create policy "requests admin read" on public.project_requests
for select to authenticated using (public.is_admin() or user_id = auth.uid());

drop policy if exists "requests admin update" on public.project_requests;
create policy "requests admin update" on public.project_requests
for update to authenticated using (public.is_admin()) with check (public.is_admin());

grant select on public.profiles to authenticated;
grant select, insert, update, delete on public.project_submissions to authenticated;
grant select, insert, update on public.project_requests to authenticated;

-- After your first signup, make YOUR account the site administrator:
-- Replace YOUR_EMAIL@example.com with your actual account email and run:
-- update public.profiles
-- set role = 'admin'
-- where id = (select id from auth.users where email = 'YOUR_EMAIL@example.com');
